apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script-configmap
data:
  initdb.sh: |-
   #!/bin/bash
   set -e
   psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER dev_admin WITH PASSWORD 'secret';
    CREATE DATABASE contactsdb;
    GRANT ALL PRIVILEGES ON DATABASE contactsdb TO dev_admin;
   EOSQL

