apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrescontacts
spec:
  selector:
    matchLabels:
      app: postgrescontacts
  replicas: 1
  template:
    metadata:
      labels:
        app: postgrescontacts
    spec:
      containers:
      - name: postgrescontacts
        image: postgres
        envFrom:
          - secretRef:
              name: postgres-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
          name: postgres-port
        volumeMounts:
          #This is the path in the container on which the mounting will take place.
            - mountPath: /var/lib/postgresql/data
              name: postgredb
            - mountPath: /docker-entrypoint-initdb.d
              name : init-script

      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-claim
        - name: init-script
          configMap:
             name: postgres-init-script-configmap

