apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    name: myingress
spec:
  rules:
  - host: insuasti-cisneros.info
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: react-service
            port: 
              number: 80
      - pathType: Prefix
        path: "/pgadmin4"
        backend:
          service:
            name: pgadmin-service
            port: 
              number: 8080

