kind: PersistentVolume
#version of ApiServer on control panel node (/api/v1) check using kubectl api-versions
apiVersion: v1
metadata:
  name: postgres-volume
  labels:
    #it is aplugin suport many luke amazon EBS azure disk etc.  local = local storage devices mounted on nodes.
    type: local
    app: postgrescontacts
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
    #many pods on shcheduled on differents nodes can read and write
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/"