apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgrescontacts
    #meant that we can use arbitrary key pair values
type: Opaque
data:
  POSTGRES_DB: Y29udGFjdHNkYg==
  POSTGRES_USER: ZGV2X2FkbWlu
  POSTGRES_PASSWORD: c2VjcmV0