apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  labels:
    app: postgres
    #meant that we can use arbitrary key pair values
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YnJ5YW5uaWNvbGFzNjdAZ21haWwuY29t
  PGADMIN_DEFAULT_PASSWORD: MTIzNDU2Nzg5
  PGADMIN_PORT: ODA4MA==